server:
  port: 8080

spring:
  datasource:
    username: ${DB_USER:aliservice}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:customer}
    password: ${DB_PASS:1376gtid}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'

  application:
    name: customer